name: CI/CD

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]
 
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag extpiotrowski/sample_flask_app
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }}|docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push Docker image to Docker Hub
      run: docker push extpiotrowski/sample_flask_app
    
    - name: Authentication
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.CLOUD_JSONKEY}}
    
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: flask-app
        region: europe-central2
        project_id: my-project-flask-384909
        image: extpiotrowski/sample_flask_app
